default: &default
  host: localhost
  adapter: postgresql
  encoding: unicode
  user: postgres
  pool: 10
  password: p0stgr3s

development:
  <<: *default
  database: selenium_development

sandbox:
  <<: *default
  database: selenium_sandbox

#production:
#  <<: *default
#  host: 127.0.0.1
#  database: selenium_production